services:
  nginx-site:
    image: "nginx:stable-alpine"
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro #откуда и куда копировать
      - ./src:/var/www/laravel
    depends_on:
      - mysql-site
      - php-site
    links:
      - node
  php-site:
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile #скачиваем php и конфигурируем
    volumes:
      - ./src:/var/www/laravel
    links:
      - node
  mysql-site:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env
    volumes:
      - ./db:/geoposition.sql

  composer: #Служебный контейнер
    build:
      context: dockerfiles
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/laravel

  artisan: #Служебный контейнер
    build:
      context: dockerfiles
      dockerfile: php.Dockerfile
    volumes:
      - ./src:/var/www/laravel
    entrypoint: ["php", "/var/www/laravel/artisan"]

  node:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - ./src:/var/www/laravel
    working_dir: /var/www/laravel
    tty: true